### ISSUE TITLE
crontab recommandations ?

### ISSUE THREAD

**Issue by lakano** [kshcherban/acme-nginx#10]
Hello,

Could you advice me about the crontab configuration for auto-renew please?
In the Rate Limits documentation, I understood that the renew is subject to the duplicate certificates limitation (5 registred domains per week).
But inside my list of 91 domains, I have 29 distinct registered domains, this mean I'll reach each time the limit per week ? 

May be I need to run the same command in crontab only one time per month ? 
Thanks for your advices :)

PS: This could be useful to add the answer in the README.md

**Comment by kshcherban** [comment]
I use following cronjob
```
12 11 10 * * root /usr/local/bin/acme-nginx -d prolinux.org -d www.prolinux.org 2>&1 >> /var/log/letsencrypt.log
```
