### ISSUE TITLE
403/404 issues

### ISSUE THREAD

**Issue by zdragon11** [kshcherban/acme-nginx#16]
[root@Aiwan ~]# acme-nginx -d jjguandan.com -d www.jjguandan.com
Mar 22 09:26:24 Trying to register account key
Mar 22 09:26:27 Already registered!
Mar 22 09:26:27 Requesting challenge
Mar 22 09:26:29 Adding nginx virtual host and completing challenge
Mar 22 09:26:29 Creating file /etc/nginx/sites-enabled/0-letsencrypt
Mar 22 09:26:38 jjguandan.com challenge did not pass: {u'status': u'invalid', u'validationRecord': [{u'url': u'http://jjguandan.com/.well-known/acme-challenge/AWKDk4h3JSxr5K5Joiy_qDOXtv0en7ReUTvO3kR_-oQ', u'hostname': u'jjguandan.com', u'addressUsed': u'58.215.161.249', u'port': u'80', u'addressesResolved': [u'58.215.161.249']}], u'keyAuthorization': u'AWKDk4h3JSxr5K5Joiy_qDOXtv0en7ReUTvO3kR_-oQ.Qp0Fln_QV6cm274adE9eZGn8KQbN21lhHMNb5OxU2u8', u'uri': u'https://acme-v01.api.letsencrypt.org/acme/challenge/mbUIzPZA_Vtwq1AyavIa78FSJ_CBVZN9kOu_o4YhhWc/847320642', u'token': u'AWKDk4h3JSxr5K5Joiy_qDOXtv0en7ReUTvO3kR_-oQ', u'error': {u'status': 403, u'type': u'urn:acme:error:unauthorized', u'detail': u'Invalid response from http://jjguandan.com/.well-known/acme-challenge/AWKDk4h3JSxr5K5Joiy_qDOXtv0en7ReUTvO3kR_-oQ: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor="white">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>"'}, u'type': u'http-01'}
Mar 22 09:26:38 removing /etc/nginx/sites-enabled/0-letsencrypt
Mar 22 09:26:38 removing /tmp/tmpS0DNKq/AWKDk4h3JSxr5K5Joiy_qDOXtv0en7ReUTvO3kR_-oQ
Mar 22 09:26:38 removing /tmp/tmpS0DNKq

it`s the error, somebody help pls!!!

**Comment by kshcherban** [comment]
Please rerun with `--debug` flag and provide here nginx configuration.

**Comment by zdragon11** [comment]
#####with --debug#####
[root@Aiwan ~]# acme-nginx -d jjguandan.com -d www.jjguandan.com --debug
Mar 22 17:34:55 Trying to register account key
Mar 22 17:34:59 Already registered!
Mar 22 17:34:59 Requesting challenge
Mar 22 17:35:02 Adding nginx virtual host and completing challenge
Mar 22 17:35:02 Creating file /etc/nginx/sites-enabled/0-letsencrypt
Mar 22 17:35:14 jjguandan.com challenge did not pass: {u'status': u'invalid', u'validationRecord': [{u'url': u'http://jjguandan.com/.well-known/acme-challenge/LXCsGC9A2BCh5tuzBr2he4rD5ryfc2Z5KDBYObcV2cw', u'hostname': u'jjguandan.com', u'addressUsed': u'58.215.161.249', u'port': u'80', u'addressesResolved': [u'58.215.161.249']}], u'keyAuthorization': u'LXCsGC9A2BCh5tuzBr2he4rD5ryfc2Z5KDBYObcV2cw.Qp0Fln_QV6cm274adE9eZGn8KQbN21lhHMNb5OxU2u8', u'uri': u'https://acme-v01.api.letsencrypt.org/acme/challenge/CIxxJnHhZtEMr_gn-_MN3oHpNh06zAgcr9flZg0E_ZU/849654096', u'token': u'LXCsGC9A2BCh5tuzBr2he4rD5ryfc2Z5KDBYObcV2cw', u'error': {u'status': 403, u'type': u'urn:acme:error:unauthorized', u'detail': u'Invalid response from http://jjguandan.com/.well-known/acme-challenge/LXCsGC9A2BCh5tuzBr2he4rD5ryfc2Z5KDBYObcV2cw: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor="white">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>"'}, u'type': u'http-01'}

#####nginx configuration#####
[root@Aiwan ~]# egrep -v "#|^$" /etc/nginx/conf.d/default.conf
server {
    listen       80;
    server_name jjguandan.com www.jjguandan.com cms.jjguandan.com wx.jjguandan.com;
    location / {
        proxy_pass http://192.168.0.102;
        root   /usr/share/nginx/html;
        index   index.html index.htm;
    }
}

nginx(centos 7), 0.102 is windows 2008 with phpstudy( php + apache), pls hava a look...

**Comment by kshcherban** [comment]
Can you please ensure that `/etc/nginx/sites-enabled/` is read by nginx? 
Also as a quick fix you can try to do so.
```
cp /etc/nginx/{sites-enabled,conf.d}/0-letsencrypt
service nginx reload
acme-nginx -d jjguandan.com -d www.jjguandan.com --debug
```

**Comment by zdragon11** [comment]
[root@Aiwan ~]# acme-nginx -d jjguandan.com -d www.jjguandan.com --debug
Mar 23 03:34:37 Trying to register account key
Mar 23 03:34:39 Already registered!
Mar 23 03:34:39 Requesting challenge
Mar 23 03:34:41 Adding nginx virtual host and completing challenge
Mar 23 03:34:41 Creating file /etc/nginx/sites-enabled/0-letsencrypt
Mar 23 03:34:51 jjguandan.com challenge did not pass: {u'status': u'invalid', u'validationRecord': [{u'url': u'http://jjguandan.com/.well-known/acme-challenge/D18-cR4_0xKcV_JkS1YXXwOb8ktu2eiEdDJUXpU_wmY', u'hostname': u'jjguandan.com', u'addressUsed': u'58.215.161.249', u'port': u'80', u'addressesResolved': [u'58.215.161.249']}], u'keyAuthorization': u'D18-cR4_0xKcV_JkS1YXXwOb8ktu2eiEdDJUXpU_wmY.Qp0Fln_QV6cm274adE9eZGn8KQbN21lhHMNb5OxU2u8', u'uri': u'https://acme-v01.api.letsencrypt.org/acme/challenge/62pVd0baZA_tfqmwS3D8lPiBBd50LW2p6ukjs3mHcA4/852270864', u'token': u'D18-cR4_0xKcV_JkS1YXXwOb8ktu2eiEdDJUXpU_wmY', u'error': {u'status': 403, u'type': u'urn:acme:error:unauthorized', u'detail': u'Invalid response from http://jjguandan.com/.well-known/acme-challenge/D18-cR4_0xKcV_JkS1YXXwOb8ktu2eiEdDJUXpU_wmY: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor="white">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>"'}, u'type': u'http-01'}
[root@Aiwan ~]# cat /etc/nginx/sites-enabled/0-letsencrypt              

server {
    listen 80;
    server_name jjguandan.com;
    location /.well-known/acme-challenge/ {
        alias /tmp/tmpbwV3aD/;
        try_files $uri =404;
    }
}[root@Aiwan ~]#cat /etc/nginx/conf.d/0-letsencrypt                     

server {
    listen 80;
    server_name jjguandan.com;
    location /.well-known/acme-challenge/ {
        alias /tmp/tmpyAXWem/;
        try_files $uri =404;
    }
}

also not ok...

**Comment by kshcherban** [comment]
Can you do `ls -la /tmp/tmpyAXWem/`?
Does jjguandan.com really point to the server you are working on?

**Comment by zdragon11** [comment]
[root@Aiwan ~]# ls -la /tmp/tmpyAXWem/
total 8
drwxrwxrwx.  2 root root   56 Mar 22 17:35 .
drwxrwxrwt. 41 root root 4096 Mar 23 09:09 ..
-rw-r--r--.  1 root root   87 Mar 22 17:35 LXCsGC9A2BCh5tuzBr2he4rD5ryfc2Z5KDBYObcV2cw

[root@Aiwan ~]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:0c:29:71:6d:60 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.249/24 brd 192.168.0.255 scope global ens33
       valid_lft forever preferred_lft forever
    inet6 fe80::6d5e:b4a7:cef6:587c/64 scope link 
       valid_lft forever preferred_lft forever
3: ens36: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:0c:29:71:6d:6a brd ff:ff:ff:ff:ff:ff
    inet 58.215.161.249/25 brd 58.215.161.255 scope global ens36
       valid_lft forever preferred_lft forever
    inet6 fe80::c070:b386:4d78:b09d/64 scope link 
       valid_lft forever preferred_lft forever
[root@Aiwan ~]# ping jjguandan.com
PING jjguandan.com (58.215.161.249) 56(84) bytes of data.
64 bytes from Aiwan (58.215.161.249): icmp_seq=1 ttl=64 time=0.032 ms
64 bytes from Aiwan (58.215.161.249): icmp_seq=2 ttl=64 time=0.036 ms

**Comment by zdragon11** [comment]
the nginx is in centos7 and resolution in, but the site is in win08 with only lan.
