### ISSUE TITLE
Doesn't work under FreeBSD 11

### ISSUE THREAD

**Issue by iron-udjin** [kshcherban/acme-nginx#17]
Apr 02 23:57:47 Trying to register account key
Apr 02 23:57:48 Already registered!
Apr 02 23:57:48 Requesting challenge
Apr 02 23:57:48 Adding nginx virtual host and completing challenge
Apr 02 23:57:48 Creating file /usr/local/etc/nginx/conf/www.conf
ps: illegal argument: nginx

usage: ps [-aCcdefHhjlmrSTuvwXxZ] [-O fmt | -o fmt] [-G gid[,gid...]]
          [-J jid[,jid...]] [-M core] [-N system]
          [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]]
       ps [-L]
Apr 02 23:57:48 Error adding virtual host ValueError max() arg is an empty sequence

It seems it expects output from Linux ps.

**Comment by kshcherban** [comment]
Hello, yes, it checks nginx pid with ps. It needs pid to reload nginx after config is changed.
Don't you use standard Linux ps?

**Comment by iron-udjin** [comment]
I'm trying to use acme-nginx under FreeBSD 11. There isn't Linux ps.

**Comment by kshcherban** [comment]
Feel free to add support for FreeBSD if you want.
https://github.com/kshcherban/acme-nginx/blob/master/acme_nginx/client.py#L27-L33
