### ISSUE TITLE
issue with specific nginx configuration 

### ISSUE THREAD

**Issue by mazyvan** [kshcherban/acme-nginx#18]
I get this error message

Apr 17 19:15:23 Creating file /etc/nginx/sites-enabled/letsencrypt
Apr 17 19:15:25 keepup.mx challenge did not pass: {u'status': u'invalid', u'validationRecord': [{u'url': u'http://keepup.mx/.well-known/acme-challenge/Vsyu3LaEUW0Y-pYa2BtulgHyGXtIA8pZ1dNoe5CEZA8', u'hostname': u'keepup.mx', u'addressUsed': u'34.195.8.218', u'port': u'80', u'addressesResolved': [u'34.195.8.218']}, {u'url': u'https://www.keepup.mx/.well-known/acme-challenge/Vsyu3LaEUW0Y-pYa2BtulgHyGXtIA8pZ1dNoe5CEZA8', u'hostname': u'www.keepup.mx', u'addressUsed': u'34.195.8.218', u'port': u'443', u'addressesResolved': [u'34.195.8.218']}], u'keyAuthorization': u'Vsyu3LaEUW0Y-pYa2BtulgHyGXtIA8pZ1dNoe5CEZA8.lSUzFJDFDeCTcxmOHb7OftqCkelue8iT4DBV8vgo6PI', u'uri': u'https://acme-v01.api.letsencrypt.org/acme/challenge/Soi8_7EbKgjVAPbtGO0nNovRAlrxCUj03UQp8k6YAEc/1039874280', u'token': u'Vsyu3LaEUW0Y-pYa2BtulgHyGXtIA8pZ1dNoe5CEZA8', u'error': {u'status': 403, u'type': u'urn:acme:error:unauthorized', u'detail': u'Invalid response from http://keepup.mx/.well-known/acme-challenge/Vsyu3LaEUW0Y-pYa2BtulgHyGXtIA8pZ1dNoe5CEZA8 [34.195.8.218]: 404'}, u'type': u'http-01'}
Apr 17 19:15:25 removing /etc/nginx/sites-enabled/letsencrypt

With this forcing https configuration.

```
 server {
        listen 80;
        server_name www.keepup.mx;
        server_name keepup.mx;
        return 301 https://$server_name$request_uri;
 }

 server {
        listen 80;
        server_name api.keepup.mx;
        return 301 https://$server_name$request_uri;
 }

 server {
        listen 443 ssl;
        server_name keepup.mx;
        ssl on;
        ssl_certificate /etc/ssl/private/letsencrypt-domain.pem;
        ssl_certificate_key /etc/ssl/private/letsencrypt-domain.key;

        return 301 https://www.keepup.mx$request_uri;
 }
```
All the request must be redirected through ssl. I'm using nginx only as a reverse proxy. So my web server is resolving the request with an 404 page.

**Comment by kshcherban** [comment]
ACME doesn't work with https, only http.

**Comment by mazyvan** [comment]
Ok. But do you have any idea of how can I renew my certificates without have to comment the https redirect?

I don't know but maybe something like acme-nginx -d www.example.com (and here -x renew-ssl.example.com)
Like making a specific channel in the server for the renewal. I don't know if this is possible. I think not because it need to check the specific subdomain. Right?

Anyway thanks for replying.

**Comment by kshcherban** [comment]
It's not possible with this script atm, i will check if it's possible to implement later.
