### ISSUE TITLE
Ip Address

### ISSUE THREAD

**Issue by androos** [kshcherban/acme-nginx#19]
I my setup i have only given specific ip addresses. With this setup your bots vhost don't work. is it possible to give an ip address for the vhost? this would do it.

**Comment by kshcherban** [comment]
AFAIK Letsencrypt works on;y with domains, you can't issue certificate if you don't own domain and can't proof it in one or another way. Please refer to https://letsencrypt.org/how-it-works/

**Comment by androos** [comment]
Sry.
what I meant was,
nginx can use this:

listen 80;

or this:

listen 1.2.3.4:80;

In my case I use the second. And your script generates a vhost which does not work for my nginx setup!
It would maybe work perfectly when you can add an ip address parameter for the 'listen [ip]:80; part of your vhost.

**Comment by androos** [comment]
So I know IPs can't have certs. :P 

OK I think I will use a script to replace the entire nginx config for the time acme runs, to circumvent this problem.
