### ISSUE TITLE
the installation stop at here, it consumes large amounts of CPU. it seems there is a infinite loop

### ISSUE THREAD

**Issue by balboliu** [kshcherban/acme-nginx#2]
`running install
running bdist_egg
running egg_info
writing requirements to acme_nginx.egg-info/requires.txt
writing acme_nginx.egg-info/PKG-INFO
writing top-level names to acme_nginx.egg-info/top_level.txt
writing dependency_links to acme_nginx.egg-info/dependency_links.txt
writing entry points to acme_nginx.egg-info/entry_points.txt
reading manifest file 'acme_nginx.egg-info/SOURCES.txt'
writing manifest file 'acme_nginx.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/acme_nginx
copying build/lib/acme_nginx/client.py -> build/bdist.linux-x86_64/egg/acme_nginx
copying build/lib/acme_nginx/__init__.py -> build/bdist.linux-x86_64/egg/acme_nginx
byte-compiling build/bdist.linux-x86_64/egg/acme_nginx/client.py to client.pyc
byte-compiling build/bdist.linux-x86_64/egg/acme_nginx/__init__.py to __init__.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying acme_nginx.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying acme_nginx.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying acme_nginx.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying acme_nginx.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying acme_nginx.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying acme_nginx.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/acme_nginx-0.0.1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing acme_nginx-0.0.1-py2.7.egg
Removing /usr/local/lib/python2.7/site-packages/acme_nginx-0.0.1-py2.7.egg
Copying acme_nginx-0.0.1-py2.7.egg to /usr/local/lib/python2.7/site-packages
acme-nginx 0.0.1 is already the active version in easy-install.pth
Installing acme-nginx script to /usr/local/bin

Installed /usr/local/lib/python2.7/site-packages/acme_nginx-0.0.1-py2.7.egg
Processing dependencies for acme-nginx==0.0.1
Searching for cryptography>=1.3.4
Reading http://mirrors.aliyun.com/pypi/simple/cryptography/
Downloading http://mirrors.aliyun.com/pypi/packages/03/1a/60984cb85cc38c4ebdfca27b32a6df6f1914959d8790f5a349608c78be61/cryptography-1.5.2.tar.gz#md5=f977a6ddb38b071213c0157fc77c62ab
Best match: cryptography 1.5.2
Processing cryptography-1.5.2.tar.gz
Writing /tmp/easy_install-kGN2EZ/cryptography-1.5.2/setup.cfg
Running cryptography-1.5.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-kGN2EZ/cryptography-1.5.2/egg-dist-tmp-8Tqq5P

Installed /tmp/easy_install-kGN2EZ/cryptography-1.5.2/.eggs/cffi-1.8.3-py2.7-linux-x86_64.egg
Searching for pycparser
Reading http://mirrors.aliyun.com/pypi/simple/pycparser/
Downloading http://mirrors.aliyun.com/pypi/packages/be/64/1bb257ffb17d01f4a38d7ce686809a736837ad4371bcc5c42ba7a715c3ac/pycparser-2.17.tar.gz#md5=ca98dcb50bc1276f230118f6af5a40c7
Best match: pycparser 2.17
Processing pycparser-2.17.tar.gz
Writing /tmp/easy_install-kGN2EZ/cryptography-1.5.2/temp/easy_install-ERrqMa/pycparser-2.17/setup.cfg
Running pycparser-2.17/setup.py -q bdist_egg --dist-dir /tmp/easy_install-kGN2EZ/cryptography-1.5.2/temp/easy_install-ERrqMa/pycparser-2.17/egg-dist-tmp-safDIw
warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
warning: no previously-included files matching 'lextab.*' found under directory 'tests'
warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
warning: no previously-included files matching 'lextab.*' found under directory 'examples'
zip_safe flag not set; analyzing archive contents...
pycparser.ply.lex: module references __file__
pycparser.ply.lex: module MAY be using inspect.getsourcefile
pycparser.ply.yacc: module references __file__
pycparser.ply.yacc: module MAY be using inspect.getsourcefile
pycparser.ply.yacc: module MAY be using inspect.stack
pycparser.ply.ygen: module references __file__
creating /tmp/easy_install-kGN2EZ/cryptography-1.5.2/.eggs/pycparser-2.17-py2.7.egg
Extracting pycparser-2.17-py2.7.egg to /tmp/easy_install-kGN2EZ/cryptography-1.5.2/.eggs

Installed /tmp/easy_install-kGN2EZ/cryptography-1.5.2/.eggs/pycparser-2.17-py2.7.egg
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*' found under directory 'vectors'`

**Comment by kshcherban** [comment]
It's because of dependencies installation: pyOpenSSL and pycrypto. These packages have C code and are compiled during installation. You can alternatively install your OS packages that contain these dependencies. I will update documentation to include Fedora/RedHat/CentOS installation instructions.
