### ISSUE TITLE
Renew fails with 403 Forbidden if umask 077

### ISSUE THREAD

**Issue by bjnord** [kshcherban/acme-nginx#22]
With latest acme-nginx pulled from Github, trying to renew my cert with:

`$ sudo acme-nginx -d dom.ain -d www.dom.ain`

I was getting this error:

`Jun 10 10:36:23 dom.ain challenge did not pass: {u'status': u'invalid', u'validationRecord': [{u'addressesResolved': [u'1.2.3.4'], u'url': u'http://dom.ain/.well-known/acme-challenge/6gQTAh5F8hT9j5n1Us1n9MdSjOSRcIMmGiJ48x36k1U', u'hostname': u'dom.ain', u'addressesTried': [], u'addressUsed': u'1.2.3.4', u'port': u'80'}], u'keyAuthorization': u'6gQTAh5F8hT9j5n1Us1n9MdSjOSRcIMmGiJ48x36k1U.k-3VezBwTzuUqD5sUVAwvJFhdJAjKdYSAfaKAiUvoAg', u'uri': u'https://acme-v01.api.letsencrypt.org/acme/challenge/5bukDnghW1k7thJ7Wka-tMOGtGnD41E9yq6izT3u6sQ/1313315139', u'token': u'6gQTAh5F8hT9j5n1Us1n9MdSjOSRcIMmGiJ48x36k1U', u'error': {u'status': 403, u'type': u'urn:acme:error:unauthorized', u'detail': u'Invalid response from http://dom.ain/.well-known/acme-challenge/6gQTAh5F8hT9j5n1Us1n9MdSjOSRcIMmGiJ48x36k1U: "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor="white">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>"'}, u'type': u'http-01'}`

It turns out my umask was `077` and acme-nginx was installing the `/etc/nginx/sites-enabled/0-letsencrypt` file as `root root 0600` which nginx couldn't read.

Either acme-nginx needs to set its own appropriate umask, or it should be sure to install the nginx config. file as `0644` or similar.

**Comment by kshcherban** [comment]
Hello @bjnord, makes sense.

**Comment by bjnord** [comment]
Perfect; thanks! (And thanks for your work on this project.)

**Comment by kshcherban** [comment]
Welcome and thanks for contributing issues.

**Comment by bjnord** [comment]
I went to renew my cert with the latest acme-nginx (including your commit 849f113 above) and it almost works, but not quite. You set the permissions of the `sites-enabled/0-letsencrypt.conf` file to 0644, and the `/tmp/XXX` directory appears to get created wide open (0777)... but the key file inside the `/tmp/XXX` directory is set to only be readable by `root` (the command is `os.chmod(key_path, 0o400)`). So nginx still can't read the file.

Changing that line to `os.chmod(key_path, 0o444)` should do the trick? Thanks!

**Comment by kshcherban** [comment]
Nginx should be able to read certificate keys, which are secure by default as nginx starts as root. But during renewal process nginx doesn't need to read certificates. Not sure about your problem. Script works for me without any issues.

**Comment by bjnord** [comment]
OK, thanks. (I solved my issue by overriding the umask before running acme-nginx.)
