### ISSUE TITLE
Is acme-nginx script can permit the use of private key ?

### ISSUE THREAD

**Issue by lakano** [kshcherban/acme-nginx#25]
Hi !
I'm using your script since many time now, thank again ! :)

I would like to enable HPKP to prevent MITM attacks, but this require to use private keys that don't expire. Let's Encrypt permit to specify a CSR but not all ACME clients permit it (--csr option on certbot ).

I've read how to enable it here: https://ithenrik.com/blog/posts/activating-http-public-key-pinning-hpkp-on-lets-encrypt 

But I would like to known if this is possible with your acme-nginx script and if this will break the auto-renew work ?

Thanks

**Comment by kshcherban** [comment]
@lakano my script doesn't recreate new private key if it already exists. Please check https://github.com/kshcherban/acme-nginx/blob/master/acme_nginx/client.py#L260

**Comment by lakano** [comment]
Thanks !
