### ISSUE TITLE
request certificate error because of the update of the Let's encrypt agreement

### ISSUE THREAD

**Issue by SimonFuu** [kshcherban/acme-nginx#26]
Hey there,
I was trying to request a new certificate via acme-nginx, but failed and got 400 response as the following image shows. I think this may cause by the update of the agreement.
![wx20171115-171501](https://user-images.githubusercontent.com/18401434/32828171-5444da96-ca29-11e7-9689-b4e2bfccfcac.png)

**Comment by SimonFuu** [comment]
https://github.com/kshcherban/acme-nginx/pull/27

**Comment by kshcherban** [comment]
Please close if it helped you.
