### ISSUE TITLE
"challenge did not pass" due to wrong path

### ISSUE THREAD

**Issue by DmitryMyadzelets** [kshcherban/acme-nginx#3]
I've got the following error (site name is changed):

    Trying to register account key
    Already registered!
    Requesting challenge
    Adding nginx virtual host and completing challenge
    Creating file / etc / nginx / sites - enabled / letsencrypt
    www.example.com challenge did not pass: {
        u 'status': u 'invalid',
        u 'validationRecord': [{
            u 'url': u 'http://www.example.com/.well-known/acme-challenge/QSXLhuSNNii5iGvW-t7cdu37POF8Wuy9UsXMImofSIY',
            u 'hostname': u 'www.example.com',
            u 'addressUsed': u '93.184.216.34',
            u 'port': u '80',
            u 'addressesResolved': [u '93.184.216.34']
        }],
        u 'keyAuthorization': u 'QSXLhuSNNii5iGvW-t7cdu37POF8Wuy9UsXMImofSIY.Ha-Tzqc8eT4bShLwWQZJzw4c8GGmhZRZXT7yx_UI9zc',
        u 'uri': u 'https://acme-v01.api.letsencrypt.org/acme/challenge/CALwG83vovIgC3Oc5HBr1zuelx22sg_9jhStvyxvxEI/344280380',
        u 'token': u 'QSXLhuSNNii5iGvW-t7cdu37POF8Wuy9UsXMImofSIY',
        u 'error': {
            u 'status': 403,
            u 'type': u 'urn:acme:error:unauthorized',
            u 'detail': u 'Invalid response from http://www.example.com/.well-known/acme-challenge/QSXLhuSNNii5iGvW-t7cdu37POF8Wuy9UsXMImofSIY: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor="white">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>"'
        },
        u 'type': u 'http-

The `/etc/nginx/sites-enabled/letsencrypt` file content:

    server {
        listen 80;
        server_name www.example.com;
        location /.well-known/acme-challenge/ {
            alias /var/tmp/tmphPO_2h;
            try_files $uri =404;
        }
    }

The `tmp` dir content:

    drwxrwxrwx 2 root root 4096 Nov 15 10:49 tmphPO_2h
    -rw-r--r-- 1 root root   87 Nov 15 10:49 tmphPO_2hQSXLhuSNNii5iGvW-t7cdu37POF8Wuy9UsXMImofSIY

The `/var/tmp/tmphPO_2h` is empty.

Probably, the script creates wrong file name. Surprisingly, the error occurs for `www.example.com` only, not for `example.com`.

**Comment by kshcherban** [comment]
Thank you for reporting that issue. Can you please elaborate if `/tmp` is a symlink to `/var/tmp` or vice versa?

**Comment by kshcherban** [comment]
8094a94 should fix the issue, please retest.

**Comment by DmitryMyadzelets** [comment]
It works now. Thank you.
The `/tmp` is absent at my setup.
