### ISSUE TITLE
ACME v2

### ISSUE THREAD

**Issue by kfoxton** [kshcherban/acme-nginx#31]
Can this be updated to support the new ACMEv2 protocol so that wildcard certificates can be generated?

Thanks!

**Comment by kshcherban** [comment]
As far as i know, under Let’s Encrypt’s policy, wildcard identifiers must be validated by a DNS-01 challenge, so order authorizations corresponding to wildcard identifiers will only offer a DNS-01 challenge. That means nginx has nothing to do here. I will check if i will implement this with manual DNS challenge step or just add HTTP challenge support for ACMEv2.

**Comment by bizlevel** [comment]
@kshcherban  now is supported wildcast domain like *.domain.com ?

**Comment by kshcherban** [comment]
Not yet, i'm working on route53 implementation at the moment. What DNS provider would you like to see supported?

**Comment by kshcherban** [comment]
Added support for ACMEv2 in #36. Please try generating wildcard certificates if you have your domain in DigitalOcean provider. Other providers will be added by request.
