### ISSUE TITLE
Nginx Error: [::1]:80 failed: Address family not supported by protocol

### ISSUE THREAD

**Issue by bizlevel** [kshcherban/acme-nginx#32]
If host no has IPv6 - impossible to create SSL.

root@server:/etc/nginx/sites-enabled# acme-nginx -d mydomain.tech --debug
Apr 10 09:22:37 Trying to register account key
Apr 10 09:22:38 Already registered!
Apr 10 09:22:38 Requesting challenge
Apr 10 09:22:38 Adding nginx virtual host and completing challenge
Apr 10 09:22:38 Creating file /etc/nginx/sites-enabled/0-letsencrypt.conf
Apr 10 09:22:38 Error adding virtual host ValueError max() arg is an empty sequence
root@server:/etc/nginx# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: configuration file /etc/nginx/nginx.conf test failed

Need get access to choose IPv4 or IPv6 or both or else.

**Comment by kshcherban** [comment]
Please provide pull request if you need this feature.
