### ISSUE TITLE
Apr 10 14:59:40 Error adding virtual host IOError [Errno 2] No such file or directory: '/etc/nginx/sites-enabled/0-letsencrypt.conf'

### ISSUE THREAD

**Issue by bizlevel** [kshcherban/acme-nginx#33]
After install fress nginx, utils not work, because sites-enabled is absent.
Also under CentOS - sites-enabled not used by nginx.

Need check used folder via nginx.conf in include variables.

**Comment by bizlevel** [comment]
On CentOS/RHEL - sites-enabled is not used
On Latest Nginx on Debian/Ubuntu - also not used.

sites-enabled - work on legacy nginx, and it will came from apache.
Now it is deprecated.

Better parse nginx.conf and use any first include folder with *.conf

**Comment by kshcherban** [comment]
Please use `--virtual-host` parameter to set proper path to virtual host file.
