### ISSUE TITLE
Error adding virtual host ValueError max() arg is an empty sequence

### ISSUE THREAD

**Issue by bizlevel** [kshcherban/acme-nginx#34]
I many times use this utils, but this error i see in first time.
Maybe because i use non-standard DNS name ?

```
root@server /etc/nginx/sites-enabled # acme-nginx -d mydomain.foundation --debug
Apr 16 20:22:31 Trying to register account key
Apr 16 20:22:32 Already registered!
Apr 16 20:22:32 Requesting challenge
Apr 16 20:22:32 Adding nginx virtual host and completing challenge
Apr 16 20:22:32 Creating file /etc/nginx/sites-enabled/0-letsencrypt.conf
Apr 16 20:22:32 Error adding virtual host ValueError max() arg is an empty sequence
root@server /etc/nginx/sites-enabled #
```

But file **0-letsencrypt.conf** is present and it looks like standard.

Also not work with **acme-nginx -d mydomain.foundation -d www.mydomain.foundation**

**Comment by kshcherban** [comment]
`Error adding virtual host ValueError max() arg is an empty sequence` means that script failed to find nginx process. Please verify that nginx is running and script can see it's processes and send signals to them.

**Comment by bizlevel** [comment]
Yes, all is fine.
