### ISSUE TITLE
fresh nginx install not able to update certificates

### ISSUE THREAD

**Issue by jdeltoft** [kshcherban/acme-nginx#35]
With a fresh install of nginx, the /etc/nginx/sites-enabled/0-letsencrypt.conf  was not working properly for me.  I was getting an error:

`Jul 09 18:34:52 mydomain.com challenge did not pass: {u'status': u'invalid', u'validationRecord': [{u'url': u'http://mydomain.com/.well-known/acme-challenge/2lop0VFwzgvwxV7mOoupzCNmcyGzipsagdKVFmZ4cmo', u'hostname': mydomain.com', u'addressUsed': u'5.2.1.2', u'port': u'80', u'addressesResolved': [u'5.2.1.2']}], u'keyAuthorization': u'2lop0VFwzgvwxV7mOoupzCNmcyGzipsagdKVFmZ4cmo.REH4y3P2z93wSGJ1OVUR11NvJLrj6RfO8ZmFa4CrpbE', u'uri': u'https://acme-v01.api.letsencrypt.org/acme/challenge/CK5qSMpL8TchpQRcTVo34OnkK0yhkz7hcx4uSontat8/5559613868', u'token': u'2lop0VFwzgvwxV7mOoupzCNmcyGzipsagdKVFmZ4cmo', u'error': {u'status': 403, u'type': u'urn:acme:error:unauthorized', u'detail': u'Invalid response from http://mydomain.com/.well-known/acme-challenge/2lop0VFwzgvwxV7mOoupzCNmcyGzipsagdKVFmZ4cmo: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor="white">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>"'}, u'type': u'http-01'}`

The problem was the configuration server file mentioned above was not being sourced.  To fix this issue I did the following:

`user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
}

http {
    include /etc/nginx/sites-enabled/*letsencrypt.conf;
    server {
        listen 443;
        server_name mydomain.com;
        access_log /var/log/nginx_access.log;
        error_log  /var/log/nginx_error.log;
        keepalive_timeout   70;
    }
}`

**Comment by kshcherban** [comment]
Please check script parameters with `--help`, it's possible to overwrite virtual host config location.
