### ISSUE TITLE
SIGHUP is not reloading nginx configuration

### ISSUE THREAD

**Issue by acejacek** [kshcherban/acme-nginx#39]
I was fighting for hours with rejected authorisations. Apparently, token file was 404 from outside.

I found, that keeping `0-letsencrypt.conf` in `sites-enabled` and sending `kill -HUP` to nginx process did nothing. Only full `systemctl daemon-reload && systemctl restart nginx` did the job. Finally I was able to curl authorisation token from `http://myserver.org/.well-known/acme-challenge/verylongfilename`.

Is it because of acme-nginx is not compatible with systemd?

**Comment by kshcherban** [comment]
Hello @acejacek,
Thanks for reporting an issue. Can you please provide your OS and nginx version so that i try to test it on local VM?

**Comment by kshcherban** [comment]
Will test on VM and share my findings. Restart of nginx shouldn't be required to reload configuration, that's a very strange behavior. Also restart is harmful because it will close all existing connections.

**Comment by acejacek** [comment]
After further investigations it look like the problem is with other enabled sites there, which prevent nginx to serve `0-letsencrypt.conf` correctly.

**Comment by acejacek** [comment]
After further investigations it look like the problem is with other enabled sites there, which prevent nginx to serve `0-letsencrypt.conf` correctly.
