### ISSUE TITLE
minor note on nginx config

### ISSUE THREAD

**Issue by gabe19** [kshcherban/acme-nginx#4]
The default nginx config in the official docker does not include /etc/nginx/sites-enabled/* by default so the vhost being written is not picked up by nginx.

**Comment by kshcherban** [comment]
You can specify desired virtual host location using `--virtual-host` command line parameter.
I didn't test this script in docker.

**Comment by gabe19** [comment]
Good point, was thinking a note on setup would help identify the config dependency.  Works successfully on docker once that is set (passed in). Thanks.
