### ISSUE TITLE
No Chain Cert

### ISSUE THREAD

**Issue by Taisgeal** [kshcherban/acme-nginx#40]
Hello,

I am using acme-nginx to get wildcard certs. I notice that I only get two certs rather than three, as per your example. 

My DNS is on Digital Ocean, DO Name servers are used  and I have nginx running on the server (droplet) that I am using to fetch certs.

What do you use as a chain file , or do you find that you don't need one ? 

Regards,
Raymond

**Comment by kshcherban** [comment]
Hello Raymond,

Letsencrypt certificate does not need chain anymore. Please check https://letsencrypt.org/certificates/

**Comment by Taisgeal** [comment]
Gotcha. Thank you very much.
