### ISSUE TITLE
KeyError: 'authorizations'

### ISSUE THREAD

**Issue by bizlevel** [kshcherban/acme-nginx#41]
Trying generate new cert, and i got this:

2018-10-01 10:11:25,942 - INFO - trying to create account key /etc/ssl/private/letsencrypt-account.key
2018-10-01 10:11:26,168 - INFO - trying to register acmev2 account
2018-10-01 10:11:26,640 - INFO - already registered
2018-10-01 10:11:26,641 - INFO - trying to create domain key
2018-10-01 10:11:26,641 - INFO - acmev2 http challenge
2018-10-01 10:11:26,641 - INFO - preparing new order
2018-10-01 10:11:27,207 - INFO - order created
Traceback (most recent call last):
  File "/usr/local/bin/acme-nginx", line 11, in <module>
    load_entry_point('acme-nginx==0.1.3', 'console_scripts', 'acme-nginx')()
  File "build/bdist.linux-x86_64/egg/acme_nginx/client.py", line 106, in main
  File "build/bdist.linux-x86_64/egg/acme_nginx/AcmeV2.py", line 189, in get_certificate
  File "build/bdist.linux-x86_64/egg/acme_nginx/AcmeV2.py", line 95, in solve_http_challenge
KeyError: 'authorizations'

**Comment by kshcherban** [comment]
Seems like intermittent error. Can you please retry version from master with `--debug` flag?

**Comment by bizlevel** [comment]
Now, i can't reproduce exactly this error, but i found why not work in my config for renew keys, and thinking how to resolve it.
1) nginx logs is:
```
2018/10/07 16:29:40 [error] 22471#22471: *5369 open() "/var/www/high/www/.well-known/acme-challenge/UTSsDBhFrDVcmd7Nupoeqc4PWJKlE77pGduJTa5WO4k" failed (2: No such file or directory), client: 64.78.149.164,
 server: high, request: "GET /.well-known/acme-challenge/UTSsDBhFrDVcmd7Nupoeqc4PWJKlE77pGduJTa5WO4k HTTP/1.1", host: "high", referrer: "http://high/.well-known/acme-challenge/UTSsDBhFr
DVcmd7Nupoeqc4PWJKlE77pGduJTa5WO4k"
2018/10/07 16:35:11 [error] 22553#22553: *5408 open() "/var/www/high/www/.well-known/acme-challenge/hChr1GG5tBZGQjvVsd5X9HmWKrG8WBOvFQc4xKa72oQ" failed (2: No such file or directory), client: 64.78.149.164,
 server: high, request: "GET /.well-known/acme-challenge/hChr1GG5tBZGQjvVsd5X9HmWKrG8WBOvFQc4xKa72oQ HTTP/1.1", host: "high", referrer: "http://high/.well-known/acme-challenge/hChr1GG5t
BZGQjvVsd5X9HmWKrG8WBOvFQc4xKa72oQ"
2018/10/07 16:38:20 [error] 22628#22628: *20 "/var/www/high/www/.well-known/acme-challenge/index.html" is not found (2: No such file or directory), client: MYIP, server: high, request: "GET /
.well-known/acme-challenge/ HTTP/1.1", host: "high"
2018/10/07 16:39:35 [error] 22628#22628: *22 open() "/var/www/high/www/.well-known/acme-challenge/hChr1GG5tBZGQjvVsd5X9HmWKrG8WBOvFQc4xKa72oQ" failed (2: No such file or directory), client: MYIP, se
rver: high, request: "GET /.well-known/acme-challenge/hChr1GG5tBZGQjvVsd5X9HmWKrG8WBOvFQc4xKa72oQ HTTP/1.1", host: "high"
2018/10/07 16:39:39 [error] 22628#22628: *22 open() "/var/www/high/www/.well-known/acme-challenge/hChr1GG5tBZGQjvVsd5X9HmWKrG8WBOvFQc4xKa72oQ" failed (2: No such file or directory), client: MYIP, se
rver: high, request: "GET /.well-known/acme-challenge/hChr1GG5tBZGQjvVsd5X9HmWKrG8WBOvFQc4xKa72oQ HTTP/1.1", host: "high"

```
2) Nginx config begit with:
```
server {
    listen 80;
    server_name DOMAIN www.DOMAIN;
    return 301 https://DOMAIN$request_uri;
}

server {
    listen 443;

    ssl on;
    ssl_certificate     /etc/ssl/private/letsencrypt-domain.pem;
    ssl_certificate_key /etc/ssl/private/letsencrypt-domain.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
...

```
3) LetsEncrypt nginx config:

```
server {
    listen 80;
    listen [::]:80;
    server_name DOMAIN1 DOMAIN2;
    location /.well-known/acme-challenge/ {
        alias /tmp/tmp9mK6fM/;
        try_files $uri =404;
    }
}

```

And nothing work, because any **HTTP** request, even letsencrypt is rewrite to **HTTPS**
And on HTTPS no acme-challenge aliases and we got 404 Error.
If i disable HTTPS rewrite - all is fine, but it is manual operation. 
How to use acme-nginx with my nginx config where is present https rewrite?
Thanks.

**Comment by kshcherban** [comment]
Nginx acme configuration should be loaded before your domain. Can you please run in debug mode and output list of `/etc/nginx/sites-enabled` directory?

**Comment by bizlevel** [comment]
It is not matter firs or second or last conf will be loaded, because in my case, even if file named 0-xxx.conf it will be first, but as i say:  Одна строка в конфиге делает полностью нерабочий скрипт
`return 301 https://DOMAIN$request_uri;
`
```
[root@bizlevel sites-enabled]# ls -la
total 64
drwxr-xr-x 2 root root 4096 Oct 18 17:18 .
drwxr-xr-x 5 root root 4096 Oct 25 12:16 ..
-rw-r--r-- 1 root root 5911 Aug  4 23:38 bizlevel.conf
-rw-r--r-- 1 root root 1189 Sep  7  2017 default.conf
-rw-r--r-- 1 root root 2615 Jul 17 21:27 incubator.conf
-rw-r--r-- 1 root root 1307 Mar  3  2017 munin.conf-
-rw-r--r-- 1 root root   96 Aug 26  2017 php-fpm.conf
-rw-r--r-- 1 root root 1044 Oct 18 16:59 phpmyadmin.conf
-rw-r--r-- 1 root root 3376 Jun  7 12:39 porto.conf
-rw-r--r-- 1 root root   50 Aug 26  2017 redis.conf
-rw-rw-rw- 1 www  www  2504 Oct 10 19:05 residences.conf-
-rw-r--r-- 1 root root 4668 Oct 18 17:18 salonbastet.conf
-rw-r--r-- 1 root root 1357 Dec  6  2017 ssl.conf-
-rw-r--r-- 1 root root  178 Sep 23  2012 status.conf
[root@bizlevel sites-enabled]#
```
