### ISSUE TITLE
Dependency on ps?

### ISSUE THREAD

**Issue by mesudip** [kshcherban/acme-nginx#46]
I tried to use the script inside a `ubuntu-alpine` continer and the following error showed up.
```
ps: unrecognized option: C
BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.

Usage: ps [-o COL1,COL2=HEADER]

Show list of processes

	-o COL1,COL2=HEADER	Select columns for display
```
I can fix the script for my usecase.
But I am just curious why `ps` voodoo was used and not  `nginx -s reload`! It's quiet obvious that the `nginx` binary would be available if user is using `acme-nginx`.

**Comment by kshcherban** [comment]
Thanks for the `nginx -s reload` idea @mesudip, i will test it and implement.
