### ISSUE TITLE
Error adding virtual host OSError [Errno 2] No such file or directory: '/var/tmp/tmp92nnDs'

### ISSUE THREAD

**Issue by mwanjajoel** [kshcherban/acme-nginx#5]
Hello, I am getting that error when I run the installer. I am using Ubuntu 14.0 LTS. Thanks for your help in advance

**Comment by kshcherban** [comment]
Hello, can you please provide full traceback?
Don't you have `/tmp` directory? AFAIK in trusty default setup is `/tmp` and not `/var/tmp` and python version is 2.6

**Comment by mwanjajoel** [comment]
Hey, I tried again and it worked. It was a memory issue on my side.
