### ISSUE TITLE
ERROR - "challenge did not pass" 

### ISSUE THREAD

**Issue by qumeta** [kshcherban/acme-nginx#52]
config 
server {
    listen 80;
    listen [::]:80;
    server_name xxx.com;
    location /.well-known/acme-challenge/ {
        alias /tmp/tmpBEQcfV/;
        try_files $uri =404;
    }
}

/tmp/tmpBEQcfV/

centos7.6
nginx 1.16.1
/tmp/tmpBEQcfV/
`
-rw-r--r-- 1 root root 87 Mar  5 20:58 TP5k7vo_2fhaDtsmla2RbpHiitF7c15HRRpYoO4uA_Q
`
`
{u'status': 403, u'type': u'urn:ietf:params:acme:error:unauthorized', u'detail': u'Invalid response from http://xxx.com/.well-known/acme-challenge/TP5k7vo_2fhaDtsmla2RbpHiitF7c15HRRpYoO4uA_Q [xxxx]: "<html>\\r\\n<head><title>404 Not Found</title></head>\\r\\n<body>\\r\\n<center><h1>404 Not Found</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n"'}
`
i find this 
https://serverfault.com/questions/742493/nginx-can-t-open-a-file-inside-tmp

**Comment by kshcherban** [comment]
Please check that your `/tmp` has proper permission, should be `1777`.
