### ISSUE TITLE
console_scripts error

### ISSUE THREAD

**Issue by GT500org** [kshcherban/acme-nginx#6]
This is an example of what happens whenever I attempt to run acme-nginx on my CentOS 6 server:
```
[root@gt500 /]# acme-nginx -d gt500.org
Traceback (most recent call last):
  File "/usr/bin/acme-nginx", line 9, in <module>
    load_entry_point('acme-nginx==0.0.2', 'console_scripts', 'acme-nginx')()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/acme_nginx/client.py", line 15, in <module>
ImportError: cannot import name check_output
```

I'm at a loss for why it's happening. I tried reinstalling acme-nginx, but that didn't help.

**Comment by kshcherban** [comment]
Hello, this is probably related to old python that has not class `check_output` in `subprocess` module.
What version of python do you have? I tested only with 2.7 and 3.

**Comment by GT500org** [comment]
This is what I have installed, and what is available on the EPEL repository for CentOS 6:
![centos6_python_packages](https://cloud.githubusercontent.com/assets/18017139/21191728/1a5a78b0-c1f4-11e6-82d8-384eb265d9c1.png)

Those are the newest versions of Python I have available on the version of CentOS 6 I have installed.

I am assuming I would have to remove Python 2.6 in order to install Python 3.4. I'm not sure whether or not that would break anything on my server. I don't use Python myself, and have a tendency to forget what does use it.

**Comment by kshcherban** [comment]
Thanks, I will try to add compatibility with python 2.6

**Comment by kshcherban** [comment]
Updated script to support python 2.6 as well, please test.

**Comment by GT500org** [comment]
That's gotten me past the error at hand, however I have run into another issue. I'm getting a 404 error for files in "gt500.org/.well-known/acme-challenge/", and my NGINX error log shows that they are not found in the root for the location that is defined in my config file.

The only instance of "well-known" I can find in the Python script appears to be part of an NGINX config file that reads as follows:
```
server {
    listen 80;
    server_name {domain};
    location /.well-known/acme-challenge/ {
        alias {alias}/;
        try_files $uri =404;
    }
}
```

I can't find where this folder, or any files contained within it, are being created by the script. Is NGINX supposed to create them? Or is a Python library supposed to create them?

Note: The roots for my domain and subdomains are in non-standard locations.

**Comment by kshcherban** [comment]
Script creates temporary directory (`{alias}`) in /tmp and temporary vhost configuration in `/etc/nginx/sites-enabled/letsencrypt` and points `/.well-known/acme-challenge/ ` to this tmp directory.
If you want to debug, just modify script not to delete this dir and vhost and see it's content after run.
I don't want to add debug mode to script because it will become more complex.

**Comment by GT500org** [comment]
It's not writing `/etc/nginx/sites-enabled/letsencrypt` and since I'm not familiar with Python I'm not entirely certain why. It does look like the variable vhost gets defined in more than one place for more than one thing, however when it is defined in the arguments it is called outside of that (method? function?) as args.vhost so I assume that should shouldn't cause an issue, but really have no clue.

I did check the permissions on `nginx_challenge` and they look OK.

**Comment by kshcherban** [comment]
It may be not writing if you don't have privileges to write there or set option `--virtual-host`.
Script logs every action, as well as that it's created something in /etc/nginx/...
https://github.com/kshcherban/acme-nginx/blob/master/acme_nginx/client.py#L281

I tested everything from my end and script worked for other people as well, so it's definitely something wrong from your side.

**Comment by GT500org** [comment]
The only error message in the terminal is the 404 error from LetsEncrypt that happens due to the missing NGINX config info. The line before that in the terminal simply says:
```
Creating file /etc/nginx/sites-enabled/letsencrypt
```
I am logged in to the terminal as root, and root is the owner of `/etc/nginx/sites-enabled` and root has permission to create and delete files.

Is there a log file with more detail saved somewhere? Is there any reason why the script might not run under the account that attempts to execute it from the terminal?

**Comment by kshcherban** [comment]
Comment out lines 315, 316 and 345 to leave temporary files.
https://github.com/kshcherban/acme-nginx/blob/master/acme_nginx/client.py#L345 
You can also run
```
python -m trace --trackcalls acme_nginx/client.py <parameters>
```
To trace all calls.

**Comment by GT500org** [comment]
I already commented all of the lines that called `os.remove()` and the script does not appear to be creating a file named `letsencrypt` in `/etc/nginx/sites-enabled`. I'll try your debug steps, and see what I find.
