### ISSUE TITLE
Folder Creation on launch and deletion of existing files

### ISSUE THREAD

**Issue by danifunker** [kshcherban/acme-nginx#7]
Hi there,

I have a big of an issue and a recommendation. 
I'm running on CentOS 7.3, I started your app, and I think I registered a private key with your app to the letsencrypt server but the folder /etc/ssl/private/ wasn't created prior to running acme-nginx so when it tried to write the key it failed. 
Dec 17 14:05:25 Error creating key IOError [Errno 2] No such file or directory: '/etc/ssl/private/letsencrypt-account.key'

I'm actually at a loss right now, it appears that the key has been issued to my system but it never saved, and now I need to recover it because I can't issue anything new at this point because the key that I have saved on my server is the wrong one.

Also, you guys are writing to the active nginx config file before you've verified everything is actually good with the certificate but delete it when it's not OK. This sounds fine, but I'm actually trying to alter existing configuration files, and when it fails the program deletes the file... That's not good. 

So, first thing, is there any way I can get my key back? Or is there a way to discard everything and start fresh from the letsencrypt side? Secondly, can you guys make the changes so the same issues don't happen to someone else?

Thanks a lot :)

**Comment by kshcherban** [comment]
Hi,

You can easily register new Letsencrypt account key without any issues.
Just create missing directory and rerun the script.

Also if script failed at the key creation step it shouldn't proceed further.
https://github.com/kshcherban/acme-nginx/blob/master/acme_nginx/client.py#L244
