### ISSUE TITLE
 Error adding virtual host 

### ISSUE THREAD

**Issue by JuliuszJ** [kshcherban/acme-nginx#8]
On Centos 7 when I run command acme-nginx -d example.com -d www.example.com,
I got following error:
Dec 26 16:13:28 Trying to register account key
Dec 26 16:13:29 Already registered!
Dec 26 16:13:29 Requesting challenge
Dec 26 16:13:29 Adding nginx virtual host and completing challenge
Dec 26 16:13:29 Creating file /etc/nginx/sites-enabled/letsencrypt
Dec 26 16:13:29 Error adding virtual host ValueError max() arg is an empty sequence

**Comment by kshcherban** [comment]
Hello,
Is nginx running?

**Comment by JuliuszJ** [comment]
Yes. It was the problem. Thank you.
