### ISSUE TITLE
Adding after the subdomains ?

### ISSUE THREAD

**Issue by lakano** [kshcherban/acme-nginx#9]
Hello,

Thanks for your script !
I added a list of domain but I forgot to add subdomains on some of them (www) 
How can I fix that please?
Do I run the same command line with only the missing subdomains (eg: -d www.alpha.com -d www.beta.com ... ) or do I run the same command line with already verified domains and missing subdomains (eg: -d alpha.com -d www.alpha.com -d beta.com -d www.beta.com ... ) ?
Thanks for your help !

**Comment by kshcherban** [comment]
Hello,

You need to specify all subdomains and domains in one command. If you have too many of them (Letsencrypt has limitation of 100 domains per cert) then please split them into two command but use different `--domain-private-key` flag.

**Comment by lakano** [comment]
@kshcherban Hum, sorry but this seems to have broken all certificates :((
I have 91 domains so under the limitation. 
I have run the same command as before and added on the line the missing subdomains, and this seems to only have verified the new one. No errors in the script. But now, if I go on the old https domain ( https://infoweb-btp.com ) the SSL certificat is broken, and the www still doesn't works ( https://www.infoweb-btp.com )

Do you have any ideas of what happened ?
Thanks for your help !

**Comment by kshcherban** [comment]
```
curl https://infoweb-btp.com/
curl: (51) SSL: certificate subject name (www.infoweb.market) does not match target host name 'infoweb-btp.com'
```

Probably you should delete old domain key (backup it first), by default it's located in `/etc/ssl/private/letsencrypt-domain.key` and try once more.

**Comment by lakano** [comment]
Good ! Thanks a lot !
